---
- name: Deploy counter-service
  hosts: ec2_instance_1
  become: true

  tasks:
    - name: Install Python 3
      yum:
        name: python3
        state: present

    - name: Install requests library
      pip:
        name: requests
        executable: pip3

    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Login to Docker Hub
      community.general.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Pull the latest Docker image
      community.general.docker_image:
        name: "{{ docker_hub_username }}/counter-service:{{ build_id }}"
        source: pull

    - name: Stop the current container if it exists
      community.general.docker_container:
        name: counter-service
        state: absent

    - name: Run the new container
      community.general.docker_container:
        name: counter-service
        image: "{{ docker_hub_username }}/counter-service:{{ build_id }}"
        published_ports:
          - "80:8000"
        restart_policy: always
        state: started
        volumes:
          - "/var/app_data/counter_service:/var/app_data/counter_service"
